# Build matrix
language: node_js
matrix:
  include:
    - node_js: '6'
      env: LINT=true
    - node_js: '4'
    - node_js: '5'
      env: UPGRADE_NPM=true
    - node_js: '6'
    - node_js: '8'
    - node_js: '10'
    - node_js: '12'

  allow_failures:
    # Run tests in the latest version of Node.js
    - node_js: 'node'

# Work around a bug on npm 3.x that causes tests to fail with Node v5
before_install:
  - if [ "$UPGRADE_NPM" ]; then npm install --global npm@4; fi

# Build script
script: ./build-script

# Build notifications
notifications:
  slack:
    secure: NOoWXmJOkn197lvsTMwnc4ACPfv6fnZuHg+y/WCT6rKVmCkyDWzcO8TGfvQUec7NkUGdH5Umeq4Ll0nDb2qxceMvEcAKaIsTxebO1AB2/ThOEM25yMi1h4ZpuMOTVPfMk8xqttJ9xOqkfgFtzczkbjYEFWMzGOX3KxjS6oOnScmbtdbB1yXbBMB75Ws0hehMEsNlRlD/76MSrlIwFHChSAUg/qJYA+mBEHOOnuMD9MbdfItmfPMu7ERxD3vrCnvE0hz++OongewofNloByTZAYBYq+OlkXvNK3Qd3H2kmhibwzVvxmo7YHOttsjXSFUUA0/URgwex/VOx75yO3D0FqJDC02w1GNQFSYGuMLnQQQI7G0CeqblBjg7Gya/YGcaASkxpsTVlOgy+K5ng5ZKtyAW7tY0YJlfpXTZEvouNlhntvhx9oa1N2hr+xrhzy3XLGa0qCsF4LSS5vQ6O9oimW02XS8LiSdyerL23F/wrm2wOizAUwV3OpNEMH5UAan1C4mlVnoNQZaVskjucxYqRDGjdxx0M8SwLBrKrh8PqURXdktjTuzj8jtMtqsMHeTswcb+IS7RrfQB1hs5EX6pEw/3RMASYsUT4Q4yo+Lc5ReU2bdvS468uQEH87MBhwqOqdjACpu+zgzBag8O9RF+BqHcutgLFpgY3yFz0TOEcQo=
